// Code generated by tools/registrygen. DO NOT EDIT.
//
// Provider type constants for all audited providers. Source of
// truth: docs/implementation/provider-matrix.yaml. The baseline
// constants ProviderOpenAI, ProviderAnthropic, ProviderAzure and
// ProviderCustom are declared by hand in types.go and are reused
// here (not redeclared). Provider types are unique in the manifest
// except "anthropic", which is shared by the anthropic and claude
// rows; a single ProviderAnthropic constant serves both.
//
// Regenerate with: go run ./tools/registrygen/

package provider

const (
	ProviderAlicode         ProviderType = "alicode"           // AUDITED: registry/alicode.js
	ProviderAlicodeIntl     ProviderType = "alicode-intl"      // AUDITED: registry/alicode-intl.js
	ProviderAlimsIntl       ProviderType = "alims-intl"        // AUDITED: registry/alims-intl.js
	ProviderAntigravity     ProviderType = "antigravity"       // AUDITED: registry/antigravity.js, executors/antigravity.js
	ProviderAssemblyai      ProviderType = "assemblyai"        // AUDITED: registry/assemblyai.js
	ProviderAwsPolly        ProviderType = "aws-polly"         // AUDITED: registry/aws-polly.js
	ProviderBlackForestLabs ProviderType = "black_forest_labs" // AUDITED: registry/black-forest-labs.js
	ProviderBlackbox        ProviderType = "blackbox"          // AUDITED: registry/blackbox.js
	ProviderBraveSearch     ProviderType = "brave_search"      // AUDITED: registry/brave-search.js
	ProviderByteplus        ProviderType = "byteplus"          // AUDITED: registry/byteplus.js
	ProviderCartesia        ProviderType = "cartesia"          // AUDITED: registry/cartesia.js
	ProviderCerebras        ProviderType = "cerebras"          // AUDITED: registry/cerebras.js
	ProviderChutes          ProviderType = "chutes"            // AUDITED: registry/chutes.js
	ProviderCline           ProviderType = "cline"             // AUDITED: registry/cline.js
	ProviderClinepass       ProviderType = "clinepass"         // AUDITED: registry/clinepass.js
	ProviderCloudflareAi    ProviderType = "cloudflare_ai"     // AUDITED: registry/cloudflare-ai.js
	ProviderCodebuddyCn     ProviderType = "codebuddy_cn"      // AUDITED: registry/codebuddy-cn.js, executors/codebuddy-cn.js
	ProviderCodex           ProviderType = "codex"             // AUDITED: registry/codex.js
	ProviderCohere          ProviderType = "cohere"            // AUDITED: registry/cohere.js
	ProviderComfyui         ProviderType = "comfyui"           // AUDITED: registry/comfyui.js
	ProviderCommandcode     ProviderType = "commandcode"       // AUDITED: registry/commandcode.js, executors/commandcode.js
	ProviderCoqui           ProviderType = "coqui"             // AUDITED: registry/coqui.js (authType=none, noAuth=true)
	ProviderCursor          ProviderType = "cursor"            // AUDITED: registry/cursor.js, executors/cursor.js
	ProviderDeepgram        ProviderType = "deepgram"          // AUDITED: registry/deepgram.js
	ProviderDeepseek        ProviderType = "deepseek"          // AUDITED: registry/deepseek.js
	ProviderEdgeTts         ProviderType = "edge_tts"          // AUDITED: registry/edge-tts.js (authType=none, noAuth=true)
	ProviderElevenlabs      ProviderType = "elevenlabs"        // AUDITED: registry/elevenlabs.js
	ProviderExa             ProviderType = "exa"               // AUDITED: registry/exa.js
	ProviderFalAi           ProviderType = "fal_ai"            // AUDITED: registry/fal-ai.js
	ProviderFeatherless     ProviderType = "featherless"       // AUDITED: registry/featherless.js
	ProviderFirecrawl       ProviderType = "firecrawl"         // AUDITED: registry/firecrawl.js
	ProviderFireworks       ProviderType = "fireworks"         // AUDITED: registry/fireworks.js
	ProviderGemini          ProviderType = "gemini"            // AUDITED: registry/gemini.js
	ProviderGeminiCli       ProviderType = "gemini_cli"        // AUDITED: registry/gemini-cli.js, executors/gemini-cli.js
	ProviderGithubModels    ProviderType = "github_models"     // AUDITED: registry/github.js, executors/github.js
	ProviderGitlab          ProviderType = "gitlab"            // AUDITED: registry/gitlab.js
	ProviderGlm             ProviderType = "glm"               // AUDITED: registry/glm.js
	ProviderGlmCn           ProviderType = "glm_cn"            // AUDITED: registry/glm-cn.js
	ProviderGooglePse       ProviderType = "google_pse"        // AUDITED: registry/google-pse.js
	ProviderGoogleTts       ProviderType = "google_tts"        // AUDITED: registry/google-tts.js (authType=none, noAuth=true)
	ProviderGrokCli         ProviderType = "grok_cli"          // AUDITED: registry/grok-cli.js, executors/grok-cli.js
	ProviderGrokWeb         ProviderType = "grok_web"          // AUDITED: registry/grok-web.js, executors/grok-web.js
	ProviderGroq            ProviderType = "groq"              // AUDITED: registry/groq.js
	ProviderHuggingface     ProviderType = "huggingface"       // AUDITED: registry/huggingface.js
	ProviderHyperbolic      ProviderType = "hyperbolic"        // AUDITED: registry/hyperbolic.js
	ProviderIflow           ProviderType = "iflow"             // AUDITED: registry/iflow.js, executors/iflow.js
	ProviderInworld         ProviderType = "inworld"           // AUDITED: registry/inworld.js
	ProviderJinaAi          ProviderType = "jina_ai"           // AUDITED: registry/jina-ai.js
	ProviderJinaReader      ProviderType = "jina_reader"       // AUDITED: registry/jina-reader.js
	ProviderKilocode        ProviderType = "kilocode"          // AUDITED: registry/kilocode.js
	ProviderKimchi          ProviderType = "kimchi"            // AUDITED: registry/kimchi.js, executors/kimchi.js
	ProviderKimi            ProviderType = "kimi"              // AUDITED: registry/kimi.js
	ProviderKiro            ProviderType = "kiro"              // AUDITED: registry/kiro.js, executors/kiro.js
	ProviderLinkup          ProviderType = "linkup"            // AUDITED: registry/linkup.js
	ProviderLocalDevice     ProviderType = "local_device"      // AUDITED: registry/local-device.js
	ProviderMimoFree        ProviderType = "mimo_free"         // AUDITED: registry/mimo-free.js, executors/mimo-free.js
	ProviderMinimax         ProviderType = "minimax"           // AUDITED: registry/minimax.js
	ProviderMinimaxCn       ProviderType = "minimax_cn"        // AUDITED: registry/minimax-cn.js
	ProviderMistral         ProviderType = "mistral"           // AUDITED: registry/mistral.js
	ProviderMmf             ProviderType = "mmf"               // AUDITED: registry/mmf.js (category=apikey, noAuth=true, double-entry with mimo-free.js)
	ProviderNanobanana      ProviderType = "nanobanana"        // AUDITED: registry/nanobanana.js
	ProviderNebius          ProviderType = "nebius"            // AUDITED: registry/nebius.js
	ProviderNvidia          ProviderType = "nvidia"            // AUDITED: registry/nvidia.js
	ProviderOllama          ProviderType = "ollama"            // AUDITED: registry/ollama.js
	ProviderOllamaLocal     ProviderType = "ollama_local"      // AUDITED: registry/ollama-local.js, executors/ollama-local.js
	ProviderOpencode        ProviderType = "opencode"          // AUDITED: registry/opencode.js
	ProviderOpencodeGo      ProviderType = "opencode_go"       // AUDITED: registry/opencode-go.js
	ProviderOpenrouter      ProviderType = "openrouter"        // AUDITED: registry/openrouter.js
	ProviderPerplexity      ProviderType = "perplexity"        // AUDITED: registry/perplexity.js
	ProviderPerplexityAgent ProviderType = "perplexity_agent"  // AUDITED: registry/perplexity-agent.js
	ProviderPerplexityWeb   ProviderType = "perplexity_web"    // AUDITED: registry/perplexity-web.js, executors/perplexity-web.js
	ProviderPlayht          ProviderType = "playht"            // AUDITED: registry/playht.js
	ProviderQoder           ProviderType = "qoder"             // AUDITED: registry/qoder.js, executors/qoder.js
	ProviderQwen            ProviderType = "qwen"              // AUDITED: registry/qwen.js, executors/qwen.js
	ProviderRecraft         ProviderType = "recraft"           // AUDITED: registry/recraft.js
	ProviderRunwayml        ProviderType = "runwayml"          // AUDITED: registry/runwayml.js
	ProviderSdwebui         ProviderType = "sdwebui"           // AUDITED: registry/sdwebui.js
	ProviderSearchapi       ProviderType = "searchapi"         // AUDITED: registry/searchapi.js
	ProviderSearxng         ProviderType = "searxng"           // AUDITED: registry/searxng.js (authType=none, noAuth=true)
	ProviderSerper          ProviderType = "serper"            // AUDITED: registry/serper.js
	ProviderSiliconflow     ProviderType = "siliconflow"       // AUDITED: registry/siliconflow.js
	ProviderStabilityAi     ProviderType = "stability_ai"      // AUDITED: registry/stability-ai.js
	ProviderTavily          ProviderType = "tavily"            // AUDITED: registry/tavily.js
	ProviderTogether        ProviderType = "together"          // AUDITED: registry/together.js
	ProviderTopaz           ProviderType = "topaz"             // AUDITED: registry/topaz.js
	ProviderTortoise        ProviderType = "tortoise"          // AUDITED: registry/tortoise.js (authType=none, noAuth=true)
	ProviderVenice          ProviderType = "venice"            // AUDITED: registry/venice.js
	ProviderVercelAiGateway ProviderType = "vercel_ai_gateway" // AUDITED: registry/vercel-ai-gateway.js
	ProviderVertex          ProviderType = "vertex"            // AUDITED: registry/vertex.js, executors/vertex.js
	ProviderVertexPartner   ProviderType = "vertex_partner"    // AUDITED: registry/vertex-partner.js, executors/vertex.js
	ProviderVolcengineArk   ProviderType = "volcengine_ark"    // AUDITED: registry/volcengine-ark.js
	ProviderVoyageAi        ProviderType = "voyage_ai"         // AUDITED: registry/voyage-ai.js
	ProviderXai             ProviderType = "xai"               // AUDITED: registry/xai.js
	ProviderXiaomiMimo      ProviderType = "xiaomi-mimo"       // AUDITED: registry/xiaomi-mimo.js
	ProviderXiaomiTokenplan ProviderType = "xiaomi-tokenplan"  // AUDITED: registry/xiaomi-tokenplan.js, executors/xiaomi-tokenplan.js
	ProviderYoucom          ProviderType = "youcom"            // AUDITED: registry/youcom.js
)
