// Package registry provides the exhaustive provider registry and the
// executor factory. Registry data is generated by tools/registrygen from
// docs/implementation/provider-matrix.yaml (P3-T01); the factory dispatches
// every registered provider type to its audited executor path.
package registry

import (
	"net/http"

	"gorouter/internal/domain/engine"
	"gorouter/internal/domain/provider"
	"gorouter/internal/engine/providers/generic"
	"gorouter/internal/engine/providers/specialized"
)

// Factory implements engine.ExecutorFactory using the generated provider
// registry. Executor selection is a registry lookup keyed by provider type,
// restricted to the formats the audited matrix row declares. Unregistered
// provider types or formats return no executor — there is no default or
// fallback executor.
type Factory struct {
	transport http.RoundTripper
}

// NewFactory creates a Factory with the given HTTP transport.
func NewFactory(transport http.RoundTripper) *Factory {
	return &Factory{transport: transport}
}

// GetExecutor returns the executor for the given provider type and request
// format. The boolean reports whether a matching executor was found.
func (f *Factory) GetExecutor(ptype provider.ProviderType, format engine.RequestFormat) (engine.Executor, bool) {
	entry, ok := ProviderRegistry[ptype]
	if !ok {
		return nil, false
	}
	if !entry.SupportsFormat(format) {
		return nil, false
	}

	if entry.ExecutorPath == "generic" {
		return f.genericExecutor(format)
	}
	return specialized.GetExecutor(ptype, f.transport)
}

// genericExecutor constructs the generic executor for a generic-path row.
// The generic package owns OpenAI-compatible and Anthropic-compatible
// executors; a generic-path row declaring another format has no executor yet.
func (f *Factory) genericExecutor(format engine.RequestFormat) (engine.Executor, bool) {
	client := generic.NewClient(generic.WithTransport(f.transport))
	switch format {
	case engine.FormatOpenAIChat, engine.FormatOpenAICompat:
		return generic.NewCompatibleOpenAIExecutor(client), true
	case engine.FormatAnthropic:
		return generic.NewCompatibleAnthropicExecutor(client), true
	default:
		return nil, false
	}
}

// Supports reports whether the factory has an executor for the given
// provider type and request format.
func (f *Factory) Supports(ptype provider.ProviderType, format engine.RequestFormat) bool {
	_, ok := f.GetExecutor(ptype, format)
	return ok
}
