package registry_test

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"gopkg.in/yaml.v3"

	"gorouter/internal/domain/engine"
	"gorouter/internal/domain/provider"
	"gorouter/internal/engine/providers/registry"
)

func repoRoot(elem ...string) string {
	return filepath.Join(append([]string{"..", "..", "..", ".."}, elem...)...)
}

type matrixEntry struct {
	ProviderID       string   `yaml:"provider_id"`
	DisplayName      string   `yaml:"display_name"`
	ProviderType     string   `yaml:"provider_type"`
	Category         string   `yaml:"category"`
	AuthType         string   `yaml:"auth_type"`
	ExecutorPath     string   `yaml:"executor_path"`
	SupportedFormats []string `yaml:"supported_formats"`
	SourceCitation   string   `yaml:"source_citation"`
}

type matrixManifest struct {
	Entries []matrixEntry `yaml:"providers"`
}

func loadMatrix(t *testing.T) []matrixEntry {
	t.Helper()
	data, err := os.ReadFile(repoRoot("docs", "implementation", "provider-matrix.yaml"))
	if err != nil {
		t.Fatalf("read matrix: %v", err)
	}
	var m matrixManifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		t.Fatalf("parse matrix: %v", err)
	}
	return m.Entries
}

func runGenerator(t *testing.T, flag string) []byte {
	t.Helper()
	cmd := exec.Command("go", "run", "./tools/registrygen/", flag)
	cmd.Dir = repoRoot()
	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("registrygen %s: %v", flag, err)
	}
	return out
}

// formatValue maps the matrix's format-constant names to the domain engine
// constant values (the matrix names the constants, the engine stores the
// wire identifiers).
func formatValue(name string) (engine.RequestFormat, bool) {
	switch name {
	case "FormatOpenAIChat":
		return engine.FormatOpenAIChat, true
	case "FormatOpenAICompat":
		return engine.FormatOpenAICompat, true
	case "FormatCodexResponses":
		return engine.FormatCodexResponses, true
	case "FormatAnthropic":
		return engine.FormatAnthropic, true
	case "FormatGemini":
		return engine.FormatGemini, true
	}
	return "", false
}

func TestRegistryGeneratedBytesMatch(t *testing.T) {
	for _, tc := range []struct {
		flag, file string
	}{
		{"-stdout-registry", "internal/engine/providers/registry/generated.go"},
		{"-stdout-types", "internal/domain/provider/types_generated.go"},
	} {
		gen := runGenerator(t, tc.flag)
		committed, err := os.ReadFile(repoRoot(tc.file))
		if err != nil {
			t.Fatalf("read %s: %v", tc.file, err)
		}
		if !bytes.Equal(gen, committed) {
			t.Errorf("%s: regenerated bytes differ from committed file", tc.file)
		}
	}
}

func TestRegistryGeneratedHeaderGuard(t *testing.T) {
	for _, f := range []string{
		"internal/engine/providers/registry/generated.go",
		"internal/domain/provider/types_generated.go",
	} {
		data, err := os.ReadFile(repoRoot(f))
		if err != nil {
			t.Fatalf("read %s: %v", f, err)
		}
		if !bytes.HasPrefix(data, []byte("// Code generated by tools/registrygen. DO NOT EDIT.")) {
			t.Errorf("%s: missing generated-code guard header", f)
		}
	}
}

func TestRegistryRowCountMatchesMatrix(t *testing.T) {
	rows := registry.RegistryRows
	matrix := loadMatrix(t)
	if len(rows) != len(matrix) {
		t.Fatalf("registry rows=%d matrix rows=%d", len(rows), len(matrix))
	}
}

func TestRegistryRowsExhaustiveAndExact(t *testing.T) {
	matrix := loadMatrix(t)
	if len(matrix) != 100 {
		t.Fatalf("matrix rows=%d want 100", len(matrix))
	}
	if len(registry.RegistryRows) != 100 {
		t.Fatalf("registry rows=%d want 100", len(registry.RegistryRows))
	}

	byID := map[string]matrixEntry{}
	for _, m := range matrix {
		if _, dup := byID[m.ProviderID]; dup {
			t.Errorf("matrix duplicate provider_id %q", m.ProviderID)
		}
		byID[m.ProviderID] = m
	}

	seen := map[string]int{}
	for _, row := range registry.RegistryRows {
		m, ok := byID[row.ProviderID]
		if !ok {
			t.Errorf("registry row %q not in matrix", row.ProviderID)
			continue
		}
		if seen[row.ProviderID]++; seen[row.ProviderID] > 1 {
			t.Errorf("registry row %q duplicated", row.ProviderID)
		}
		if row.DisplayName != m.DisplayName {
			t.Errorf("%s display_name=%q want %q", row.ProviderID, row.DisplayName, m.DisplayName)
		}
		if row.Category != m.Category {
			t.Errorf("%s category=%q want %q", row.ProviderID, row.Category, m.Category)
		}
		if row.AuthType != m.AuthType {
			t.Errorf("%s auth_type=%q want %q", row.ProviderID, row.AuthType, m.AuthType)
		}
		if row.ExecutorPath != m.ExecutorPath {
			t.Errorf("%s executor_path=%q want %q", row.ProviderID, row.ExecutorPath, m.ExecutorPath)
		}
		if row.SourceCitation != m.SourceCitation {
			t.Errorf("%s citation=%q want %q", row.ProviderID, row.SourceCitation, m.SourceCitation)
		}
		if len(row.Formats) != len(m.SupportedFormats) {
			t.Errorf("%s formats=%v want %v", row.ProviderID, row.Formats, m.SupportedFormats)
			continue
		}
		for i, f := range row.Formats {
			want, ok := formatValue(m.SupportedFormats[i])
			if !ok {
				t.Errorf("%s unknown matrix format %q", row.ProviderID, m.SupportedFormats[i])
				continue
			}
			if f != want {
				t.Errorf("%s format[%d]=%q want %q", row.ProviderID, i, f, m.SupportedFormats[i])
			}
		}
	}
}

func TestRegistryEveryMatrixTypeResolvesToEntry(t *testing.T) {
	matrix := loadMatrix(t)
	unique := map[string]string{} // provider_type -> provider_id
	for _, m := range matrix {
		unique[m.ProviderType] = m.ProviderID
	}
	for ptype, pid := range unique {
		if _, ok := registry.ProviderRegistry[provider.ProviderType(ptype)]; !ok {
			t.Errorf("matrix provider_type %q (%s) missing from ProviderRegistry", ptype, pid)
		}
	}
	for ptype, entry := range registry.ProviderRegistry {
		if entry.ProviderID == "" {
			t.Errorf("registry key %q has empty entry", ptype)
		}
		if entry.ExecutorPath == "" {
			t.Errorf("registry key %q has empty executor path", ptype)
		}
		for _, f := range entry.Formats {
			switch f {
			case engine.FormatOpenAIChat, engine.FormatOpenAICompat,
				engine.FormatCodexResponses, engine.FormatAnthropic,
				engine.FormatGemini:
			default:
				t.Errorf("registry key %q unknown format %q", ptype, f)
			}
		}
	}
}

func TestRegistryNoOrphanRowsOrTypes(t *testing.T) {
	matrix := loadMatrix(t)
	matrixIDs := map[string]bool{}
	matrixTypes := map[string]bool{}
	for _, m := range matrix {
		matrixIDs[m.ProviderID] = true
		matrixTypes[m.ProviderType] = true
	}
	for _, row := range registry.RegistryRows {
		if !matrixIDs[row.ProviderID] {
			t.Errorf("registry row %q has no matrix owner", row.ProviderID)
		}
	}
	for ptype := range registry.ProviderRegistry {
		if !matrixTypes[string(ptype)] {
			t.Errorf("registry key %q has no matrix owner", ptype)
		}
	}
}

func TestFactoryDispatchCoverage(t *testing.T) {
	f := registry.NewFactory(nil)
	matrix := loadMatrix(t)

	// Every audited matrix row must dispatch to a real executor: there is
	// no allowlist and no documented gap. A row that cannot resolve would
	// mean the factory or the matrix is wrong.
	for _, m := range matrix {
		_, ok := registry.ProviderRegistry[provider.ProviderType(m.ProviderType)]
		if !ok {
			t.Errorf("no registry entry for %s", m.ProviderID)
			continue
		}
		for _, name := range m.SupportedFormats {
			fmt, ok := formatValue(name)
			if !ok {
				t.Errorf("%s unknown matrix format %q", m.ProviderID, name)
				continue
			}
			exec, found := f.GetExecutor(provider.ProviderType(m.ProviderType), fmt)
			if !found {
				t.Errorf("factory: no executor for %s (%s, %s)", m.ProviderID, m.ExecutorPath, name)
				continue
			}
			if !exec.SupportsFormat(fmt) {
				t.Errorf("executor for %s does not support %s", m.ProviderID, name)
			}
		}
	}
}

func TestFactoryRejectsUnknownTypeAndFormat(t *testing.T) {
	f := registry.NewFactory(nil)
	if _, ok := f.GetExecutor(provider.ProviderType("not-a-provider"), engine.FormatOpenAIChat); ok {
		t.Error("unknown provider type resolved")
	}
	if _, ok := f.GetExecutor(provider.ProviderOpenAI, engine.FormatGemini); ok {
		t.Error("openai resolved unsupported format")
	}
}

func TestFactoryCodexResponses(t *testing.T) {
	f := registry.NewFactory(nil)
	exec, ok := f.GetExecutor(provider.ProviderCodex, engine.FormatCodexResponses)
	if !ok {
		t.Fatal("codex executor not found")
	}
	if !exec.SupportsFormat(engine.FormatCodexResponses) {
		t.Error("codex executor does not support FormatCodexResponses")
	}
}

// TestFactoryGeminiIdentityMapping asserts the audited identity split: the
// gemini row (registry/gemini.js) dispatches to the native Gemini executor and
// the gemini-cli row (registry/gemini-cli.js, executors/gemini-cli.js) stays on
// the Gemini CLI executor. Both rows share executor_path specialized/gemini,
// so identity is the discriminator.
func TestFactoryGeminiIdentityMapping(t *testing.T) {
	f := registry.NewFactory(nil)

	gemini, ok := f.GetExecutor(provider.ProviderGemini, engine.FormatGemini)
	if !ok {
		t.Fatal("factory: no executor for ProviderGemini")
	}
	if gemini.ProviderType() != provider.ProviderGemini {
		t.Errorf("gemini executor identity = %q, want %q", gemini.ProviderType(), provider.ProviderGemini)
	}

	cli, ok := f.GetExecutor(provider.ProviderGeminiCli, engine.FormatGemini)
	if !ok {
		t.Fatal("factory: no executor for ProviderGeminiCli")
	}
	if cli.ProviderType() != provider.ProviderGeminiCli {
		t.Errorf("gemini-cli executor identity = %q, want %q", cli.ProviderType(), provider.ProviderGeminiCli)
	}

	if gemini.ProviderType() == cli.ProviderType() {
		t.Error("gemini and gemini-cli must map to distinct executors")
	}
}
